### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by MrYakobo** [rs222kn/TimeEditApi#3]
Hi. I was playing around today with this tool, but I really can't seem like getting the hang of it. Like, I do the `npm install timeeditapi --save`, and then try to launch your example given in the README.md, but it doesn't work. From node, I get:
```
const getScheduleByDate = _getSchedule => (id, date = new Date()) =>
                                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Jakob\Documents\GitHub\timeedit\app.js:1:83)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by MrYakobo** [comment]
Just checked my node version. It was 4.5... :) It works now with latest version. 💃
